package main

import (
	"context"
	pluginv1 "github.com/Silo-Server/silo-plugin-sdk/pkg/pluginproto/silo/plugin/v1"
)

func recommendationPage(_ context.Context) (*pluginv1.HandleHTTPResponse, error) {
	return &pluginv1.HandleHTTPResponse{StatusCode: 200, Headers: map[string]string{"Content-Type": "text/html; charset=utf-8", "Cache-Control": "no-store", "X-Content-Type-Options": "nosniff"}, Body: []byte(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Stash recommendations</title><style>
 :root{color-scheme:dark light;font:16px system-ui;background:light-dark(#f4f5f7,#111318);color:light-dark(#20232a,#edf0f5)}body{max-width:1200px;margin:auto;padding:32px}h1{font-size:32px;margin-bottom:8px}p{line-height:1.5}.muted{opacity:.7}button{font:inherit;cursor:pointer;padding:10px 16px;border:1px solid #78808d66;border-radius:8px;background:light-dark(#fff,#252b36);color:inherit;margin:4px}button:disabled{opacity:.5}section{border:1px solid #78808d44;border-radius:14px;padding:20px;margin-top:20px}details{margin-top:16px}summary{cursor:pointer;font-weight:650;padding:8px}ol{padding-left:24px}li{padding:10px 0;border-bottom:1px solid #78808d33}.reason{font-size:13px;opacity:.75;display:block;margin:5px 0}.warning{color:light-dark(#8c4700,#ffc184)}.stats{display:flex;gap:20px;flex-wrap:wrap}a{color:light-dark(#2156b9,#a6c5ff)}.pill{display:inline-block;font-size:12px;border:1px solid #78808d66;border-radius:12px;padding:3px 8px}#notice{min-height:24px}
 </style></head><body><h1>Stash recommendations</h1><p class="muted">Weekly picks from ratings, explicit activity and favourites. Up to 50 items per collection.</p><div><button id="preview">Generate preview</button><button id="publish">Build collections</button><button id="reload">Refresh report</button><a id="json-report" href="#">JSON report</a></div><p id="notice" role="status"></p><div id="report"></div><script>
 const $=id=>document.getElementById(id);let current;const base=location.pathname.replace(/\/$/,'');
 function el(tag,text,cls){const x=document.createElement(tag);if(text!==undefined)x.textContent=text;if(cls)x.className=cls;return x}
 async function request(path,body){const r=await fetch(base+'/'+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||d.status||'Request failed');return d}
 async function load(){try{current=await request('report');render(current);$('notice').textContent='Report refreshed'}catch(e){$('notice').textContent=e.message}}
 function render(d){const root=$('report');root.replaceChildren();const r=d.report||{};root.append(el('h2',r.status||'No report yet'));const stats=el('div',undefined,'stats');for(const [k,v] of Object.entries({'Period':r.week||'—','Mode':r.preview?'Preview':'Publish','Model':r.model||'gpt-6-luna','API cost':'$'+Number(r.usage?.cost_usd||0).toFixed(4),'Unsettled reservation':'$'+Number(r.usage?.reserved_usd||0).toFixed(4)}))stats.append(el('span',k+': '+v));root.append(stats);if(r.status==='running')root.append(el('p','The worker is still running. Refresh to see the final result.'));for(const w of r.warnings||[])root.append(el('p',w,'warning'));
 for(const lib of r.libraries||[]){const box=el('section');box.append(el('h2','Library '+lib.library_id),el('p',lib.matched_scenes+' verified matches · '+lib.feedback_scenes+' scenes with feedback'));for(const w of lib.warnings||[])box.append(el('p',w,'warning'));if(lib.evaluation?.status==='complete')box.append(el('p','Historical check: '+lib.evaluation.hits+' of '+lib.evaluation.targets+' held-out positive targets found; studio baseline '+lib.evaluation.studio_baseline_hits+'. '+lib.evaluation.note,'muted'));
 for(const c of lib.collections||[]){const details=el('details'),summary=el('summary',c.title+' ('+(c.picks||[]).length+')');details.append(summary,el('p',c.description));const list=el('ol');for(const p of c.picks||[]){const item=el('li');item.append(el('strong',p.title||'Scene '+p.id),el('span',' '+p.confidence+' confidence','pill'),el('span',(p.reasons||[]).join(' · '),'reason'));const dismiss=el('button','Dismiss');dismiss.onclick=async()=>{try{await request('dismiss',{library_id:lib.library_id,scene_id:p.id});dismiss.disabled=true;dismiss.textContent='Dismissed for next update'}catch(e){$('notice').textContent=e.message}};item.append(dismiss);list.append(item)}details.append(list);box.append(details)}root.append(box)} }
 for(const [id,path]of [['preview','preview'],['publish','run']])$(id).onclick=async()=>{try{$('notice').textContent='Starting…';await request(path,{});$('notice').textContent='Worker started. Refresh the report for its final result.'}catch(e){$('notice').textContent=e.message}};$('reload').onclick=load;$('json-report').href=base+'/report';load();
 </script></body></html>`)}, nil
}
