package main

import (
	"context"
	pluginv1 "github.com/Silo-Server/silo-plugin-sdk/pkg/pluginproto/silo/plugin/v1"
)

func recommendationPage(_ context.Context) (*pluginv1.HandleHTTPResponse, error) {
	return &pluginv1.HandleHTTPResponse{StatusCode: 200, Headers: map[string]string{"Content-Type": "text/html; charset=utf-8", "Cache-Control": "no-store", "X-Content-Type-Options": "nosniff"}, Body: []byte(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Stash recommendations</title><style>
 :root{color-scheme:dark light;font:16px system-ui;background:light-dark(#f4f5f7,#111318);color:light-dark(#20232a,#edf0f5)}body{max-width:1200px;margin:auto;padding:32px}h1{font-size:32px;margin-bottom:8px}p{line-height:1.5}.muted{opacity:.7}button{font:inherit;cursor:pointer;padding:10px 16px;border:1px solid #78808d66;border-radius:8px;background:light-dark(#fff,#252b36);color:inherit;margin:4px}button:disabled{opacity:.5}section{border:1px solid #78808d44;border-radius:14px;padding:20px;margin-top:20px}details{margin-top:16px}summary{cursor:pointer;font-weight:650;padding:8px}ol{padding-left:24px}li{padding:10px 0;border-bottom:1px solid #78808d33}.reason{font-size:13px;opacity:.75;display:block;margin:5px 0}.warning{color:light-dark(#8c4700,#ffc184)}.stats{display:flex;gap:20px;flex-wrap:wrap}a{color:light-dark(#2156b9,#a6c5ff)}.pill{display:inline-block;font-size:12px;border:1px solid #78808d66;border-radius:12px;padding:3px 8px}#notice{min-height:24px}
 </style></head><body><h1>Stash recommendations</h1><p class="muted">Weekly picks from ratings, explicit activity and favourites. Up to 500 items per collection. Reports and generated selections are retained for six months.</p><div><button id="preview">Generate preview</button><button id="publish">Build collections</button><button id="reload">Refresh report</button><a id="json-report" href="#">JSON report</a></div><p><label for="report-history">Saved reports:</label> <select id="report-history"><option value="">Latest report</option></select></p><p id="notice" role="status"></p><div id="report"></div><script>
 const $=id=>document.getElementById(id);let current;const base=location.pathname.replace(/\/admin\/?$/,'').replace(/\/$/,'');
 function el(tag,text,cls){const x=document.createElement(tag);if(text!==undefined)x.textContent=text;if(cls)x.className=cls;return x}
 // This public shell contains no report data. Silo authorises every data/action route.
 function sessionHeaders(){const h={};try{const token=localStorage.getItem('access_token');if(token){h.Authorization='Bearer '+token;const profile=localStorage.getItem('profile_id');if(profile){h['X-Profile-Id']=profile;h['X-Profile-Token']=localStorage.getItem('profile_token')||''}}}catch{}return h}
 async function refreshSession(){try{const token=localStorage.getItem('refresh_token');if(!token)return false;const r=await fetch('/api/v2/auth/refresh',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refresh_token:token}),credentials:'same-origin'});if(!r.ok)return false;const d=await r.json();if(!d.access_token)return false;localStorage.setItem('access_token',d.access_token);if(d.refresh_token)localStorage.setItem('refresh_token',d.refresh_token);return true}catch{return false}}
 async function launch(){let h=sessionHeaders();if(!h.Authorization)return false;let r=await fetch('/api/v2/auth/plugin-launch',{method:'POST',headers:h,credentials:'same-origin'});if(r.status===401&&await refreshSession()){h=sessionHeaders();r=await fetch('/api/v2/auth/plugin-launch',{method:'POST',headers:h,credentials:'same-origin'})}return r.ok}
 async function request(path,body){const opts={credentials:'same-origin',headers:sessionHeaders()};if(body!==undefined){opts.method='POST';opts.headers['Content-Type']='application/json';opts.body=JSON.stringify(body)}let r=await fetch(base+'/'+path,opts);if(r.status===401&&await launch()){opts.headers={...opts.headers,...sessionHeaders()};r=await fetch(base+'/'+path,opts)}if(r.status===401||r.status===403)throw Error('Your Silo administrator session has expired or this profile is locked. Sign in or unlock your administrator profile in Silo, then refresh this page.');let d;try{d=await r.json()}catch{throw Error('Silo returned an unexpected response (HTTP '+r.status+'). Refresh the page or sign in to Silo.')}if(!r.ok)throw Error(d.error||d.status||'Request failed (HTTP '+r.status+')');return d}

 async function load(){try{current=await request('report');render(current);await loadHistory();$('notice').textContent='Report refreshed'}catch(e){$('notice').textContent=e.message}}
 async function loadHistory(){const d=await request('history');const select=$('report-history');const previous=select.value;select.replaceChildren();const latest=el('option','Latest report');latest.value='';select.append(latest);for(const r of d.reports||[]){const o=el('option',new Date(r.started_at).toLocaleString()+' · '+r.status+(r.preview?' · preview':''));o.value=r.id;select.append(o)}select.value=previous}
 $('report-history').onchange=async()=>{try{const id=$('report-history').value;current=id?await request('history',{report_id:id}):await request('report');render(current);$('notice').textContent=id?'Viewing saved report':'Viewing latest report'}catch(e){$('notice').textContent=e.message}};
 function render(d){const root=$('report');root.replaceChildren();const r=d.report||{};root.append(el('h2',r.status||'No report yet'));const stats=el('div',undefined,'stats');for(const [k,v] of Object.entries({'Period':r.week||'—','Mode':r.preview?'Preview':'Publish','Model':r.model||'gpt-6-luna','Estimated API cost':'$'+Number(r.usage?.cost_usd||0).toFixed(4),'Unsettled reservation':'$'+Number(r.usage?.reserved_usd||0).toFixed(4)}))stats.append(el('span',k+': '+v));root.append(stats);if(r.archive)root.append(el('p','JAVBeacon archive: '+(r.archive.archived_scenes||0)+' snapshots, '+(r.archive.archived_events||0)+' events; '+(r.archive.matched_events_added||0)+' missing events merged; '+(r.archive.history_only_releases||0)+' removed releases used for preferences ('+(r.archive.history_only_library_assigned||0)+' assigned to a library); '+(r.archive.unresolved_active_scenes||0)+' active snapshots could not be resolved.','muted'));root.append(el('p','Cost is calculated from reported tokens, not verified billing. OpenAI’s Costs dashboard is authoritative. Cached-input discounts are included when reported; historical estimates may omit them.','muted'));if(r.status==='running')root.append(el('p',d.worker_active_on_this_process?'Building: '+(r.phase||'Reading source data')+'. Refresh to see the final result.':'This build has not saved its final result. It may be running on another server; after an interruption, recovery waits for the previous reservation to expire.')); for(const w of r.warnings||[])root.append(el('p',w,'warning'));
 for(const lib of r.libraries||[]){const box=el('section');box.append(el('h2','Library '+lib.library_id),el('p',lib.matched_scenes+' verified matches · '+lib.feedback_scenes+' scenes with feedback'));for(const w of lib.warnings||[])box.append(el('p',w,'warning'));if(lib.evaluation?.status==='complete')box.append(el('p','Historical check: '+lib.evaluation.hits+' of '+lib.evaluation.targets+' held-out positive targets found; studio baseline '+lib.evaluation.studio_baseline_hits+'. '+lib.evaluation.note,'muted'));
 for(const c of lib.collections||[]){const details=el('details'),summary=el('summary',c.title+' ('+(c.picks||[]).length+')');details.append(summary,el('p',c.description));if(c.ranking_reuse){const x=c.ranking_reuse;details.append(el('p','Reused Luna priorities for '+x.covered_candidates+' / '+x.total_candidates+' candidates ('+x.saved_candidates+' using saved priorities). No additional API calls.','muted'))}const list=el('ol');for(const p of c.picks||[]){const item=el('li');item.append(el('strong',p.title||'Scene '+p.id),el('span',' '+p.confidence+' confidence','pill'),el('span',(p.reasons||[]).join(' · '),'reason'));const dismiss=el('button','Dismiss');dismiss.disabled=!!d.historical;dismiss.onclick=async()=>{try{await request('dismiss',{library_id:lib.library_id,scene_id:p.id});dismiss.disabled=true;dismiss.textContent='Dismissed for next update'}catch(e){$('notice').textContent=e.message}};item.append(dismiss);list.append(item)}details.append(list);box.append(details)}root.append(box)} }
 for(const [id,path]of [['preview','preview'],['publish','run']])$(id).onclick=async()=>{try{$('notice').textContent='Starting…';await request(path,{});$('notice').textContent='Worker started. Refresh the report for its final result.'}catch(e){$('notice').textContent=e.message}};$('reload').onclick=load;$('json-report').href=base+'/report';$('json-report').onclick=async e=>{e.preventDefault();try{const data=current||await request('report');const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=el('a');a.href=url;a.download='stash-recommendations-'+(data.report?.week||'report')+'.json';a.click();URL.revokeObjectURL(url)}catch(err){$('notice').textContent=err.message}};load();
 </script></body></html>`)}, nil
}
